{% set name = "flake8-executable" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flake8-executable-{{ version }}.tar.gz
  sha256: 619fe023e00c3d8e5113521d7200e1ebb04587c12d157f9a2fb167feb8cae66b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - flake8 >=3.0.0

test:
  imports:
    - flake8_executable
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xuhdev/flake8-executable
  summary: A Flake8 plugin for checking executable permissions and shebangs.
  license: LGPL-3.0 AND GPL-3.0
  license_file:
    - COPYING.GPL
    - COPYING

extra:
  recipe-maintainers:
    - rxm7706
